"""Recovery — roll back an orchestration project to the state after a specific change.

Used when a late change broke the build/design and we want to re-run only the
affected changes without losing earlier merged work.

Safe operations:
- Backs up state.json before any mutation
- Creates a git tag before reset (recoverable via reflog)
- Atomic execution: restores state.json on partial failure
- Refuses to run if orchestrator/sentinel is alive

Usage:
    from set_orch.recovery import recover_to_change
    recover_to_change(project_path, "shopping-cart", dry_run=False, yes=True)
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import signal
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from .state import Change, OrchestratorState, load_state, locked_state
from .subprocess_utils import run_command, run_git

logger = logging.getLogger(__name__)


class RecoveryError(Exception):
    """Recovery operation failed (validation or execution)."""

    pass


@dataclass
class RecoveryPlan:
    target_change: str
    target_commit: str
    rollback_changes: list[str] = field(default_factory=list)
    branches_to_delete: list[str] = field(default_factory=list)
    worktrees_to_remove: list[str] = field(default_factory=list)
    archive_dirs_to_restore: list[Path] = field(default_factory=list)
    state_changes_to_reset: list[str] = field(default_factory=list)
    backup_tag: str = ""
    first_rolled_back_phase: int = 1
    # fix-iss descendants generated by the ISS pipeline from failed parents.
    # Fully removed from state (not reset) + openspec dirs deleted.
    fix_iss_changes_to_delete: list[str] = field(default_factory=list)
    fix_iss_dirs_to_delete: list[Path] = field(default_factory=list)
    # Journals, issues, manifest — per-change artefacts to purge so a re-run
    # does not inherit stale history.
    journals_to_delete: list[Path] = field(default_factory=list)
    issues_to_remove: list[str] = field(default_factory=list)  # ISS-IDs
    e2e_manifest_to_delete: Optional[Path] = None


# ─── Validation ────────────────────────────────────────────────────────────


def _is_pid_alive(pid: int) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
        return True
    except (OSError, ProcessLookupError):
        return False


def _resolve_state_file(project_path: Path) -> Path:
    """State lives at `<project>/orchestration-state.json` — the canonical
    location used by set-orchestrate, set-merge, and the engine. LineagePaths
    exposes a different path for a layout that was never adopted."""
    return project_path / "orchestration-state.json"


def _validate_project(project_path: Path, target_change: str) -> tuple[OrchestratorState, Change]:
    """Validate project is in a recoverable state. Returns (state, target_change_obj)."""
    state_file = _resolve_state_file(project_path)
    if not state_file.is_file():
        raise RecoveryError(f"No state file in {project_path} (resolved {state_file})")

    try:
        state = load_state(str(state_file))
    except Exception as e:
        raise RecoveryError(f"Failed to load state.json: {e}")

    orch_pid = state.extras.get("orchestrator_pid") or getattr(state, "orchestrator_pid", None)
    if orch_pid and _is_pid_alive(int(orch_pid)):
        raise RecoveryError(
            f"Orchestrator running (PID {orch_pid}). Stop it first."
        )

    sentinel_pid_file = project_path / ".set" / "sentinel.pid"
    if sentinel_pid_file.is_file():
        try:
            pid = int(sentinel_pid_file.read_text().strip())
            if _is_pid_alive(pid):
                raise RecoveryError(
                    f"Sentinel running (PID {pid}). Stop it first."
                )
        except (ValueError, OSError):
            pass

    target = next((c for c in state.changes if c.name == target_change), None)
    if not target:
        available = ", ".join(c.name for c in state.changes if c.status == "merged")
        raise RecoveryError(
            f"Target change '{target_change}' not found. Merged changes: {available}"
        )
    if target.status != "merged":
        raise RecoveryError(
            f"Target '{target_change}' is '{target.status}', not merged — "
            f"cannot recover to non-merged state"
        )

    return state, target


# ─── Plan building ─────────────────────────────────────────────────────────


def _find_target_commit(project_path: Path, target_change: str) -> str:
    """Find the archive commit SHA for the target change."""
    # Try archive commit first (most precise)
    r = run_git(
        "log", "--all", "--grep", f"archive {target_change}",
        "--format=%H", "-1",
        cwd=str(project_path),
    )
    if r.exit_code == 0 and r.stdout.strip():
        return r.stdout.strip().split("\n")[0]

    # Fall back to merge commit
    r = run_git(
        "log", "--all", "--grep", f"merge.*{target_change}|Merged {target_change}",
        "--format=%H", "-1", "-E",
        cwd=str(project_path),
    )
    if r.exit_code == 0 and r.stdout.strip():
        return r.stdout.strip().split("\n")[0]

    # Last resort: any commit mentioning the change name
    r = run_git(
        "log", "--all", "--grep", target_change, "--format=%H", "-1",
        cwd=str(project_path),
    )
    if r.exit_code == 0 and r.stdout.strip():
        return r.stdout.strip().split("\n")[0]

    raise RecoveryError(f"No commit found for change '{target_change}'")


def _find_archive_dirs(project_path: Path, change_name: str) -> list[Path]:
    """Find archived openspec change dirs for a given change name."""
    archive_root = project_path / "openspec" / "changes" / "archive"
    if not archive_root.is_dir():
        return []
    matches = []
    for entry in archive_root.iterdir():
        if entry.is_dir() and entry.name.endswith(f"-{change_name}"):
            matches.append(entry)
    return matches


def _list_git_worktrees(project_path: Path) -> list[tuple[str, Optional[str]]]:
    """Return [(worktree_path, branch_name_or_None)] by parsing `git worktree list --porcelain`.

    The state's `worktree_path` may be stale (point at archived `.removed.*`
    suffixed dir); this is the authoritative source.
    """
    r = run_git("worktree", "list", "--porcelain", cwd=str(project_path))
    if r.exit_code != 0:
        return []
    worktrees: list[tuple[str, Optional[str]]] = []
    cur_path: Optional[str] = None
    cur_branch: Optional[str] = None
    for line in r.stdout.splitlines():
        if line.startswith("worktree "):
            if cur_path is not None:
                worktrees.append((cur_path, cur_branch))
            cur_path = line[len("worktree "):].strip()
            cur_branch = None
        elif line.startswith("branch refs/heads/"):
            cur_branch = line[len("branch refs/heads/"):].strip()
    if cur_path is not None:
        worktrees.append((cur_path, cur_branch))
    return worktrees


def _find_fix_iss_descendants(
    state: OrchestratorState,
    rolled_back: set[str],
    project_path: Path,
) -> list[tuple[str, Optional[Path]]]:
    """Find fix-iss-* state changes whose parent is being rolled back.

    State entries for fix-iss changes are often truncated (e.g.
    'fix-iss-001-catalog-listings-and') while the issues registry keeps the
    full change_name ('fix-iss-001-catalog-listings-and-homepage').  Match
    via registry lookup + prefix tolerance.
    """
    registry_file = project_path / ".set" / "issues" / "registry.json"
    iss_entries: list[tuple[str, str]] = []  # (change_name_full, affected_change)
    if registry_file.is_file():
        try:
            with open(registry_file) as f:
                reg = json.load(f)
            for i in reg.get("issues", []):
                cn = i.get("change_name")
                aff = i.get("affected_change")
                if cn and aff:
                    iss_entries.append((cn, aff))
        except (json.JSONDecodeError, OSError):
            pass

    descendants: list[tuple[str, Optional[Path]]] = []
    for ch in state.changes:
        if not ch.name.startswith("fix-iss"):
            continue
        matched = False
        for cn_full, aff in iss_entries:
            if aff not in rolled_back:
                continue
            if cn_full == ch.name or cn_full.startswith(ch.name):
                matched = True
                break
        if not matched:
            continue
        dir_path = project_path / "openspec" / "changes" / ch.name
        descendants.append((ch.name, dir_path if dir_path.is_dir() else None))
    return descendants


def _find_issues_to_remove(
    project_path: Path,
    rolled_back: set[str],
    fix_iss_names: set[str],
) -> list[str]:
    """Return ISS-IDs whose `affected_change` or `change_name` matches the rollback scope."""
    registry_file = project_path / ".set" / "issues" / "registry.json"
    if not registry_file.is_file():
        return []
    try:
        with open(registry_file) as f:
            reg = json.load(f)
    except (json.JSONDecodeError, OSError):
        return []
    ids: list[str] = []
    for i in reg.get("issues", []):
        aff = i.get("affected_change") or ""
        cn = i.get("change_name") or ""
        if aff in rolled_back:
            ids.append(i.get("id", ""))
            continue
        # fix-iss state names may be truncated — match any fix-iss name whose
        # registry change_name starts with the truncated state name.
        for fn in fix_iss_names:
            if cn == fn or cn.startswith(fn):
                ids.append(i.get("id", ""))
                break
    return [i for i in ids if i]


def _e2e_manifest_references_rollback(
    project_path: Path,
    rolled_back: set[str],
) -> Optional[Path]:
    """Return manifest path if it references any rolled-back change, else None."""
    manifest = project_path / "e2e-manifest.json"
    if not manifest.is_file():
        return None
    try:
        with open(manifest) as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return None
    cur = data.get("change")
    reqs = data.get("requirements_by_change") or []
    if cur in rolled_back or any(r in rolled_back for r in reqs):
        return manifest
    return None


def _build_recovery_plan(
    state: OrchestratorState,
    target_change: str,
    target_commit: str,
    project_path: Path,
) -> RecoveryPlan:
    target_idx = next(
        i for i, c in enumerate(state.changes) if c.name == target_change
    )

    # All changes after target that have been touched (merged, running, etc.).
    # `failed:*` (e.g. failed:stuck_no_progress, failed:retry_budget_exhausted)
    # are terminal statuses introduced after this tool was written — match by
    # prefix so orphaned worktrees/branches from failed attempts also get
    # cleaned up.
    rollback_statuses = {
        "merged", "verifying", "integrating", "running", "done",
        "verify-failed", "integration-failed", "integration-e2e-failed",
        "stalled",
    }
    rollback_changes = [
        c for c in state.changes[target_idx + 1 :]
        if c.status in rollback_statuses or c.status.startswith("failed:")
    ]

    if not rollback_changes:
        raise RecoveryError(
            f"Nothing to roll back — no changes after '{target_change}' have been touched"
        )

    # Collect archive dirs
    archive_dirs = []
    for c in rollback_changes:
        archive_dirs.extend(_find_archive_dirs(project_path, c.name))

    # First rolled-back change's phase (where we'll resume from)
    first_phase = rollback_changes[0].phase

    rollback_names = {c.name for c in rollback_changes}

    # Worktrees: merge state's `worktree_path` + git's authoritative list.
    # State paths can be stale (point at archived `.removed.*` suffix), while
    # git may still have worktrees the state no longer references.
    worktrees_to_remove: list[str] = []
    seen: set[str] = set()
    for c in rollback_changes:
        if c.worktree_path and c.worktree_path not in seen:
            worktrees_to_remove.append(c.worktree_path)
            seen.add(c.worktree_path)
    branch_names = {f"change/{n}" for n in rollback_names}
    for wt_path, wt_branch in _list_git_worktrees(project_path):
        if wt_branch in branch_names and wt_path not in seen:
            worktrees_to_remove.append(wt_path)
            seen.add(wt_path)

    # fix-iss descendants — fully delete from state, not just reset
    fix_iss_descendants = _find_fix_iss_descendants(state, rollback_names, project_path)
    fix_iss_names = {n for n, _ in fix_iss_descendants}
    fix_iss_dirs = [p for _, p in fix_iss_descendants if p is not None]

    # Per-change artefacts to purge
    journals_to_delete: list[Path] = []
    journals_dir = project_path / "journals"
    if journals_dir.is_dir():
        for name in rollback_names | fix_iss_names:
            j = journals_dir / f"{name}.jsonl"
            if j.is_file():
                journals_to_delete.append(j)

    issues_to_remove = _find_issues_to_remove(project_path, rollback_names, fix_iss_names)
    e2e_manifest = _e2e_manifest_references_rollback(project_path, rollback_names)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return RecoveryPlan(
        target_change=target_change,
        target_commit=target_commit,
        rollback_changes=[c.name for c in rollback_changes],
        branches_to_delete=[f"change/{c.name}" for c in rollback_changes],
        worktrees_to_remove=worktrees_to_remove,
        archive_dirs_to_restore=archive_dirs,
        state_changes_to_reset=[c.name for c in rollback_changes],
        backup_tag=f"recovery-backup-{timestamp}",
        first_rolled_back_phase=first_phase,
        fix_iss_changes_to_delete=sorted(fix_iss_names),
        fix_iss_dirs_to_delete=fix_iss_dirs,
        journals_to_delete=journals_to_delete,
        issues_to_remove=issues_to_remove,
        e2e_manifest_to_delete=e2e_manifest,
    )


# ─── Preview ────────────────────────────────────────────────────────────────


def render_preview(plan: RecoveryPlan, project_path: Path) -> str:
    lines = [
        "Recovery Plan",
        "=" * 60,
        f"Project: {project_path}",
        f"Target:  {plan.target_change} (commit {plan.target_commit[:8]})",
        "",
        f"After rollback, ready to re-run ({len(plan.rollback_changes)}):",
    ]
    for c in plan.rollback_changes:
        lines.append(f"  - {c}")
    lines.append("")

    lines.append("Will undo:")
    lines.append("")
    lines.append("  Git:")
    lines.append(f"    - reset main → {plan.target_commit[:8]}")
    for branch in plan.branches_to_delete:
        lines.append(f"    - delete branch {branch}")
    lines.append(f"    - tag rollback point as {plan.backup_tag}")
    lines.append("")

    if plan.worktrees_to_remove:
        lines.append("  Worktrees:")
        for wt in plan.worktrees_to_remove:
            lines.append(f"    - {wt}")
        lines.append("")

    if plan.archive_dirs_to_restore:
        lines.append("  OpenSpec (un-archive):")
        for ad in plan.archive_dirs_to_restore:
            lines.append(f"    - {ad.name} → openspec/changes/")
        lines.append("")

    if plan.fix_iss_changes_to_delete:
        lines.append("  fix-iss descendants (full delete):")
        for n in plan.fix_iss_changes_to_delete:
            lines.append(f"    - state.changes.{n}")
        for d in plan.fix_iss_dirs_to_delete:
            lines.append(f"    - openspec/changes/{d.name}/")
        lines.append("")

    lines.append("  State:")
    for ch in plan.state_changes_to_reset:
        lines.append(f"    - {ch}: → pending (clear tokens, gates, retries, worktree)")
    lines.append("    - merge_queue: cleared")
    lines.append(f"    - current_phase: → {plan.first_rolled_back_phase}")
    lines.append("    - status: stopped (requires explicit restart)")
    lines.append("")

    if plan.journals_to_delete:
        lines.append("  Journals (delete):")
        for j in plan.journals_to_delete:
            lines.append(f"    - journals/{j.name}")
        lines.append("")

    if plan.issues_to_remove:
        lines.append("  Issues (registry + investigations):")
        for iss in plan.issues_to_remove:
            lines.append(f"    - {iss}")
        lines.append("    - .set/issues/processed_findings.json → cleared")
        lines.append("")

    if plan.e2e_manifest_to_delete:
        lines.append("  Stale artefacts:")
        lines.append(f"    - {plan.e2e_manifest_to_delete.name} (regenerates on next e2e)")
        lines.append("")

    _state_base = _resolve_state_file(project_path).name
    lines.append("  Backup:")
    lines.append(f"    - {_state_base} → {_state_base}.bak.{plan.backup_tag.split('-', 2)[-1]}")
    lines.append(f"    - git tag {plan.backup_tag}")

    return "\n".join(lines)


# ─── State reset helper ─────────────────────────────────────────────────────


def reset_change_to_pending(ch: Change) -> None:
    """Return a `Change` to its pre-dispatch state.

    Clears everything produced by a prior dispatch/verify/integrate cycle:
    - worktree/agent pointers and timestamps
    - token counters
    - gate outputs, results, stats, screenshots
    - per-gate timing
    - retry counters (verify, merge, redispatch) and wall-clock retry budget
    - merge-stall counter (`merge_stall_attempts`) and its companions
      (`ff_retry_count`, `total_merge_attempts`) — so a re-dispatched change
      starts with a fresh merge-stall circuit-breaker budget.
    - gate-retry cache (`gate_retry_tracking`, `last_gate_fingerprint`,
      `verify_retry_index`, `gate_recheck_done`) — without this, the next
      dispatch can hit a stale `last_verdict_sha` that points to a commit the
      recovery's `git reset --hard` just discarded.
    - stuck-loop breaker state (both top-level `stuck_loop_count` and the
      `stuck_fingerprint` / `stuck_head_sha` entries in `extras`).
    - context-token baselines and fix-iss parent pointer.

    Preserves the change's *identity*: name, scope, phase, depends_on,
    requirements, gate_hints, model, skip flags.

    IMPORTANT: this helper does NOT touch on-disk artifacts. The `change/<name>`
    branch and `{project}-wt-<name>` worktree directory are left intact even
    though `ch.worktree_path` is cleared. Callers that want a clean re-dispatch
    MUST pair this reset with artifact removal:

    - The circuit-breaker path (`IssueManager._retry_parent_after_resolved`)
      calls `set_orch.change_cleanup.cleanup_change_artifacts(name, project_path)`
      before the reset.
    - The recovery CLI's `_execute_plan` iterates `plan.worktrees_to_remove`
      and `plan.branches_to_delete` with its own idempotent git calls (the
      plan may reference archived-suffix paths that the canonical helper
      would not find).

    Skipping artifact cleanup seeds a `{name}-N` collision on the next
    dispatch — the exact failure mode that fix-merge-worktree-collision
    addresses.
    """
    ch.status = "pending"
    ch.current_step = None
    ch.worktree_path = None
    ch.ralph_pid = None
    ch.started_at = None
    ch.completed_at = None

    # Tokens
    ch.tokens_used = 0
    ch.tokens_used_prev = 0
    ch.input_tokens = 0
    ch.output_tokens = 0
    ch.cache_read_tokens = 0
    ch.cache_create_tokens = 0
    ch.input_tokens_prev = 0
    ch.output_tokens_prev = 0
    ch.cache_read_tokens_prev = 0
    ch.cache_create_tokens_prev = 0

    # Gate results
    for attr in (
        "build_result", "test_result", "e2e_result", "review_result",
        "smoke_result", "scope_check_result", "rules_result",
        "e2e_coverage_result", "test_coverage",
    ):
        if hasattr(ch, attr):
            setattr(ch, attr, None)
    for attr in ("test_stats", "smoke_stats"):
        if hasattr(ch, attr):
            setattr(ch, attr, None)

    # Gate outputs
    for attr in (
        "build_output", "test_output", "e2e_output", "smoke_output",
        "review_output", "scope_check_output", "rules_output",
        "e2e_coverage_output",
    ):
        if hasattr(ch, attr):
            setattr(ch, attr, None)

    # Screenshot bookkeeping
    for attr in ("smoke_screenshot_dir", "e2e_screenshot_dir"):
        if hasattr(ch, attr):
            setattr(ch, attr, "")
    for attr in ("smoke_screenshot_count", "e2e_screenshot_count"):
        if hasattr(ch, attr):
            setattr(ch, attr, 0)

    # Gate timing
    for attr in (
        "gate_total_ms", "gate_build_ms", "gate_test_ms", "gate_e2e_ms",
        "gate_review_ms", "gate_smoke_ms", "gate_scope_check_ms",
        "gate_rules_ms", "gate_e2e_coverage_ms", "gate_verify_ms",
    ):
        if hasattr(ch, attr):
            setattr(ch, attr, 0)

    # Retry counters and cache
    for attr in (
        "verify_retry_count", "verify_retry_index",
        "redispatch_count", "merge_retry_count", "stuck_loop_count",
        "retry_wall_time_ms",
    ):
        if hasattr(ch, attr):
            setattr(ch, attr, 0)
    for attr in ("last_gate_fingerprint", "token_runaway_baseline",
                 "fix_iss_child", "assigned_e2e_port"):
        if hasattr(ch, attr):
            setattr(ch, attr, None)
    if hasattr(ch, "gate_recheck_done"):
        ch.gate_recheck_done = False
    if hasattr(ch, "gate_retry_tracking"):
        ch.gate_retry_tracking = {}
    if hasattr(ch, "touched_file_globs"):
        ch.touched_file_globs = []

    # Context-token baselines
    for attr in ("context_tokens_start", "context_tokens_end",
                 "context_breakdown_start"):
        if hasattr(ch, attr):
            setattr(ch, attr, None)

    # Watchdog
    if hasattr(ch, "watchdog"):
        ch.watchdog = None

    # Extras — clear every key that tracks a prior dispatch. Keep any keys
    # not listed here (user-extensions, unknown future fields).
    for k in (
        "merge_retry_count", "integration_retry_count",
        "integration_e2e_retry_count", "retry_context",
        "merge_rebase_pending", "stalled_at",
        "stuck_fingerprint", "stuck_head_sha",
        "merge_stall_attempts", "ff_retry_count", "total_merge_attempts",
    ):
        ch.extras.pop(k, None)


# ─── Execution ──────────────────────────────────────────────────────────────


def _kill_zombie_agents(state: OrchestratorState, change_names: list[str]) -> None:
    for ch in state.changes:
        if ch.name in change_names and ch.ralph_pid and _is_pid_alive(ch.ralph_pid):
            logger.warning("Killing zombie agent for %s (PID %d)", ch.name, ch.ralph_pid)
            try:
                os.kill(ch.ralph_pid, signal.SIGTERM)
            except OSError as e:
                logger.warning("Failed to kill PID %d: %s", ch.ralph_pid, e)


def _execute_plan(project_path: Path, plan: RecoveryPlan, state: OrchestratorState) -> None:
    state_file = _resolve_state_file(project_path)
    backup_suffix = plan.backup_tag.split("-", 2)[-1]
    state_backup = state_file.with_suffix(state_file.suffix + f".bak.{backup_suffix}")

    # Backup state.json
    shutil.copy(str(state_file), str(state_backup))
    logger.info("Backed up state.json → %s", state_backup.name)

    # Create git safety tag
    r = run_git("tag", plan.backup_tag, cwd=str(project_path))
    if r.exit_code != 0:
        logger.warning("Failed to create backup tag: %s", r.stderr)
    else:
        logger.info("Created backup tag: %s", plan.backup_tag)

    try:
        # 1. Kill zombie agents
        _kill_zombie_agents(state, plan.state_changes_to_reset)

        # 2. Remove worktrees
        for wt_path in plan.worktrees_to_remove:
            if not os.path.isdir(wt_path):
                logger.info("Worktree dir already gone: %s", wt_path)
                continue
            r = run_git("worktree", "remove", "--force", wt_path, cwd=str(project_path))
            if r.exit_code == 0:
                logger.info("Removed worktree: %s", wt_path)
            else:
                logger.warning("worktree remove failed (%s): %s", wt_path, r.stderr)

        # 3. Delete branches
        for branch in plan.branches_to_delete:
            r = run_git("branch", "-D", branch, cwd=str(project_path))
            if r.exit_code == 0:
                logger.info("Deleted branch: %s", branch)
            else:
                logger.info("Branch delete skipped (%s): %s", branch, r.stderr.strip())

        # 4. Save archived change dirs to temp BEFORE git reset deletes them
        import tempfile
        _archive_temp = Path(tempfile.mkdtemp(prefix="set-recovery-archive-"))
        _saved_archives: list[tuple[Path, str]] = []  # (temp_path, change_name)
        for archive_dir in plan.archive_dirs_to_restore:
            if not archive_dir.is_dir():
                continue
            parts = archive_dir.name.split("-")
            for i, p in enumerate(parts):
                if not p.isdigit() and not (len(p) == 4 and p.isdigit()):
                    name_start = i
                    break
            else:
                name_start = 0
            change_name = "-".join(parts[name_start:])
            temp_dest = _archive_temp / change_name
            shutil.copytree(str(archive_dir), str(temp_dest))
            _saved_archives.append((temp_dest, change_name))
            logger.info("Saved archive to temp: %s", change_name)

        # 5. Reset main (this deletes archive dirs from git tree)
        r = run_git("reset", "--hard", plan.target_commit, cwd=str(project_path))
        if r.exit_code != 0:
            shutil.rmtree(str(_archive_temp), ignore_errors=True)
            raise RecoveryError(f"git reset failed: {r.stderr}")
        logger.info("Reset main to %s", plan.target_commit[:8])

        # 6. Restore archived changes from temp
        changes_root = project_path / "openspec" / "changes"
        changes_root.mkdir(parents=True, exist_ok=True)
        for temp_path, change_name in _saved_archives:
            dest = changes_root / change_name
            if dest.exists():
                logger.warning("Change dir already exists, skipping restore: %s", dest)
                continue
            shutil.move(str(temp_path), str(dest))
            logger.info("Restored archive: %s → openspec/changes/%s", change_name, change_name)
        shutil.rmtree(str(_archive_temp), ignore_errors=True)

        # 6. Reset state.json
        fix_iss_set = set(plan.fix_iss_changes_to_delete)
        with locked_state(str(state_file)) as s:
            for ch in s.changes:
                if ch.name in plan.state_changes_to_reset:
                    reset_change_to_pending(ch)
            if fix_iss_set:
                before = len(s.changes)
                s.changes = [c for c in s.changes if c.name not in fix_iss_set]
                logger.info(
                    "Removed %d fix-iss descendants from state", before - len(s.changes)
                )
            s.merge_queue = []
            s.status = "stopped"
            s.extras["current_phase"] = plan.first_rolled_back_phase
            logger.info("Reset state for %d changes", len(plan.state_changes_to_reset))

        # 7. Delete fix-iss openspec dirs
        for d in plan.fix_iss_dirs_to_delete:
            if d.is_dir():
                shutil.rmtree(str(d))
                logger.info("Removed fix-iss openspec dir: %s", d.name)

        # 8. Delete per-change journals
        for j in plan.journals_to_delete:
            try:
                j.unlink()
                logger.info("Removed journal: %s", j.name)
            except FileNotFoundError:
                pass

        # 9. Delete stale e2e-manifest
        if plan.e2e_manifest_to_delete and plan.e2e_manifest_to_delete.is_file():
            plan.e2e_manifest_to_delete.unlink()
            logger.info("Removed stale e2e-manifest.json")

        # 10. Clean up progress/tracking files that reference rolled-back changes
        _reset_progress_files(project_path, plan)

    except Exception as e:
        # Atomic rollback: restore state.json
        shutil.copy(str(state_backup), str(state_file))
        logger.error("Recovery failed mid-way: %s. State restored from backup.", e)
        raise RecoveryError(
            f"Recovery failed: {e}\n"
            f"State.json restored from {state_backup.name}.\n"
            f"To undo git changes: git reset --hard {plan.backup_tag}"
        )


def _reset_progress_files(project_path: Path, plan: RecoveryPlan) -> None:
    """Clean up progress/tracking files that reference rolled-back changes."""
    rolled_back = set(plan.state_changes_to_reset)

    # coverage-merged.json: remove entries for rolled-back REQs
    coverage_merged = project_path / "set" / "orchestration" / "digest" / "coverage-merged.json"
    if coverage_merged.is_file():
        try:
            with open(coverage_merged) as f:
                coverage = json.load(f)
            # Each key is a REQ-ID with a "change" field
            keys_to_remove = [
                k for k, v in coverage.items()
                if isinstance(v, dict) and v.get("change") in rolled_back
            ]
            for k in keys_to_remove:
                del coverage[k]
            with open(coverage_merged, "w") as f:
                json.dump(coverage, f, indent=2)
            if keys_to_remove:
                logger.info("Removed %d coverage entries for rolled-back changes", len(keys_to_remove))
        except (json.JSONDecodeError, OSError, KeyError) as e:
            logger.warning("Failed to clean coverage-merged.json: %s", e)

    # review-findings: filter out lines for rolled-back changes (LineagePaths.review_findings)
    from .paths import LineagePaths as _LP_rfc
    review_findings = Path(_LP_rfc(str(project_path)).review_findings)
    if review_findings.is_file():
        try:
            lines = review_findings.read_text().splitlines()
            kept = [
                l for l in lines
                if not any(f'"change": "{c}"' in l or f'"change":"{c}"' in l for c in rolled_back)
            ]
            review_findings.write_text("\n".join(kept) + "\n" if kept else "")
            removed = len(lines) - len(kept)
            if removed:
                logger.info("Removed %d review findings for rolled-back changes", removed)
        except OSError as e:
            logger.warning("Failed to clean review findings: %s", e)

    # runtime logs for rolled-back changes
    runtime_root = Path.home() / ".local" / "share" / "set-core" / "runtime" / project_path.name
    logs_dir = runtime_root / "logs" / "changes"
    if logs_dir.is_dir():
        for change_name in rolled_back:
            change_log_dir = logs_dir / change_name
            if change_log_dir.is_dir():
                shutil.rmtree(str(change_log_dir))
                logger.info("Removed runtime logs for %s", change_name)

    # Issues registry: remove issues by ID (pre-computed from affected_change
    # and change_name fields — schema uses `affected_change`/`change_name`,
    # not `change`, so filtering by `change` never matched anything).
    issues_dir = project_path / ".set" / "issues"
    registry_file = issues_dir / "registry.json"
    issue_ids_to_remove = set(plan.issues_to_remove)
    if registry_file.is_file() and issue_ids_to_remove:
        try:
            with open(registry_file) as f:
                registry = json.load(f)
            issues = registry.get("issues", [])
            kept = [i for i in issues if i.get("id") not in issue_ids_to_remove]
            removed = len(issues) - len(kept)
            registry["issues"] = kept
            with open(registry_file, "w") as f:
                json.dump(registry, f, indent=2)
            if removed:
                logger.info("Removed %d issues for rolled-back changes", removed)
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to clean issues registry: %s", e)

    # Investigation markdowns for removed ISS-IDs
    investigations = issues_dir / "investigations"
    if investigations.is_dir():
        for iss_id in issue_ids_to_remove:
            md = investigations / f"{iss_id}.md"
            if md.is_file():
                md.unlink()
                logger.info("Removed investigation: %s", md.name)

    # processed_findings.json — stale finding cursor from the killed session.
    # Reset so a fresh sentinel run reprocesses findings from scratch.
    pf = issues_dir / "processed_findings.json"
    if pf.is_file():
        try:
            pf.write_text("[]\n")
            logger.info("Cleared processed_findings.json")
        except OSError as e:
            logger.warning("Failed to clear processed_findings.json: %s", e)


# ─── Main entry point ──────────────────────────────────────────────────────


def recover_to_change(
    project_path: Path,
    target_change: str,
    *,
    dry_run: bool = False,
    yes: bool = False,
) -> RecoveryPlan:
    """Roll back project to the state after target_change was archived.

    Args:
        project_path: Project root (contains the resolver's state file)
        target_change: Name of merged change to recover to
        dry_run: If True, show plan but don't execute
        yes: If True, skip confirmation prompt

    Returns:
        The executed RecoveryPlan

    Raises:
        RecoveryError: validation or execution failure
    """
    state, target = _validate_project(project_path, target_change)
    target_commit = _find_target_commit(project_path, target_change)
    plan = _build_recovery_plan(state, target_change, target_commit, project_path)

    print(render_preview(plan, project_path))
    print()

    if dry_run:
        print("[DRY RUN — no changes made]")
        return plan

    if not yes:
        confirm = input("Type 'yes' to proceed: ").strip().lower()
        if confirm != "yes":
            raise RecoveryError("Cancelled by user")

    _execute_plan(project_path, plan, state)

    print()
    print("Recovery complete.")
    print()
    print(f"Project rolled back to: {target_change}")
    print(f"Backup tag: {plan.backup_tag}")
    print()
    _state_base = _resolve_state_file(project_path).name
    print("To undo: git reset --hard " + plan.backup_tag)
    print(f"         cp {_state_base}.bak.{plan.backup_tag.split('-', 2)[-1]} {_state_base}")
    return plan
