"""Tests for Sections 4b (per-lineage plan/digest retention) and 8 (session markers)."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "lib"))

from tests.lib import test_paths as tp

from set_orch.api.activity import _collect_session_boundaries
from set_orch.engine import (
    _rotate_event_streams,
    _rotate_plan_and_digest_for_new_lineage,
)
from set_orch.paths import SetRuntime
from set_orch.state import init_state, load_state
from set_orch.types import slug


@pytest.fixture(autouse=True)
def isolated_runtime(tmp_path, monkeypatch):
    import set_orch.paths as paths_mod
    monkeypatch.setattr(paths_mod, "SET_TOOLS_DATA_DIR",
                        str(tmp_path / "xdg" / "set-core"))
    yield


def _setup_v1_project(tmp_path):
    proj = tmp_path / "proj"
    proj.mkdir()
    rt = SetRuntime(str(proj))
    rt.ensure_dirs()

    plan_path = tp.plan_file(rt.orchestration_dir)
    domains_path = os.path.join(rt.orchestration_dir, "orchestration-plan-domains.json")
    digest_dir = proj / "set" / "orchestration" / "digest"
    digest_dir.mkdir(parents=True, exist_ok=True)
    (digest_dir / "REQ-1.md").write_text("# v1 req")

    with open(plan_path, "w") as fh:
        json.dump({
            "plan_version": 1,
            "input_path": "docs/spec-v1.md",
            "changes": [{"name": "v1-change", "scope": "s",
                         "complexity": "M", "phase": 1}],
        }, fh)
    with open(domains_path, "w") as fh:
        json.dump({"domains": [{"name": "v1-domain"}]}, fh)
    return proj, rt


# ---------------------------------------------------------------------------
# Section 4b — per-lineage rename on sentinel start
# ---------------------------------------------------------------------------


def test_rotate_plan_renames_v1_files_when_v2_starts(tmp_path):
    proj, rt = _setup_v1_project(tmp_path)
    out_slug = _rotate_plan_and_digest_for_new_lineage(
        str(proj), "docs/spec-v2.md",
    )
    assert out_slug == slug("docs/spec-v1.md")

    expected_plan = os.path.join(
        rt.orchestration_dir, f"orchestration-plan-{out_slug}.json",
    )
    expected_domains = os.path.join(
        rt.orchestration_dir, f"orchestration-plan-domains-{out_slug}.json",
    )
    expected_digest = proj / "set" / "orchestration" / f"digest-{out_slug}"
    assert os.path.isfile(expected_plan)
    assert os.path.isfile(expected_domains)
    assert expected_digest.is_dir()
    # Live files are gone (they would be regenerated by the new sentinel).
    assert not os.path.exists(tp.plan_file(rt.orchestration_dir))
    assert not (proj / "set" / "orchestration" / "digest").exists()


def test_rotate_plan_no_op_for_same_lineage(tmp_path):
    proj, rt = _setup_v1_project(tmp_path)
    result = _rotate_plan_and_digest_for_new_lineage(
        str(proj), "docs/spec-v1.md",  # same as on-disk
    )
    assert result is None
    # Live files still in place.
    assert os.path.isfile(tp.plan_file(rt.orchestration_dir))
    assert (proj / "set" / "orchestration" / "digest").is_dir()


def test_rotate_plan_no_op_when_no_plan_exists(tmp_path):
    proj = tmp_path / "fresh"
    proj.mkdir()
    result = _rotate_plan_and_digest_for_new_lineage(
        str(proj), "docs/spec-v2.md",
    )
    assert result is None


def test_rotate_plan_handles_corrupt_plan(tmp_path, caplog):
    import logging
    proj = tmp_path / "proj"
    proj.mkdir()
    rt = SetRuntime(str(proj))
    rt.ensure_dirs()
    with open(tp.plan_file(rt.orchestration_dir), "w") as fh:
        fh.write("{ broken")
    with caplog.at_level(logging.WARNING, logger="set_orch.engine"):
        result = _rotate_plan_and_digest_for_new_lineage(
            str(proj), "docs/spec-v2.md",
        )
    assert result is None
    assert any("rotate_plan" in rec.message for rec in caplog.records)


# ---------------------------------------------------------------------------
# Section 8 — session boundary extraction
# ---------------------------------------------------------------------------


def _make_cycle_file(proj, n, *, session_id, lineage="docs/spec.md", ts=None):
    if ts is None:
        ts = f"2026-01-{n:02d}T00:00:00+00:00"
    path = proj / f"orchestration-events-cycle{n}.jsonl"
    with open(path, "w") as fh:
        fh.write(json.dumps({
            "type": "CYCLE_HEADER",
            "ts": ts,
            "cycle": n,
            "spec_lineage_id": lineage,
            "sentinel_session_id": session_id,
            "plan_version": 1,
        }) + "\n")
        fh.write(json.dumps({
            "type": "DISPATCH", "ts": ts, "change": f"c-{n}",
        }) + "\n")


def test_session_boundaries_emit_one_marker_per_transition(tmp_path):
    proj = tmp_path / "proj"
    proj.mkdir()
    _make_cycle_file(proj, 1, session_id="session-A")
    _make_cycle_file(proj, 2, session_id="session-A")  # no transition
    _make_cycle_file(proj, 3, session_id="session-B")  # boundary 1
    _make_cycle_file(proj, 4, session_id="session-C")  # boundary 2
    boundaries = _collect_session_boundaries(proj)
    # Two transitions → two markers.
    assert len(boundaries) == 2
    sids = [b["session_id"] for b in boundaries]
    assert sids == ["session-B", "session-C"]


def test_session_boundaries_empty_when_no_cycles(tmp_path):
    proj = tmp_path / "proj"
    proj.mkdir()
    assert _collect_session_boundaries(proj) == []


def test_session_boundaries_empty_for_single_session(tmp_path):
    proj = tmp_path / "proj"
    proj.mkdir()
    _make_cycle_file(proj, 1, session_id="only-one")
    _make_cycle_file(proj, 2, session_id="only-one")
    assert _collect_session_boundaries(proj) == []


def test_session_boundary_carries_lineage_metadata(tmp_path):
    proj = tmp_path / "proj"
    proj.mkdir()
    _make_cycle_file(proj, 1, session_id="A", lineage="docs/spec-v1.md")
    _make_cycle_file(proj, 2, session_id="B", lineage="docs/spec-v2.md")
    out = _collect_session_boundaries(proj)
    assert len(out) == 1
    assert out[0]["spec_lineage_id"] == "docs/spec-v2.md"
    assert out[0]["session_id"] == "B"
